### PR TITLE
lock column scrolling

### PR DESCRIPTION
**Pull request by bezanis**
Fix scrolling when moving from left columns to main columns on a single scroll, and vice versa

### CODE REVIEW

**Comment by colin0117** [comment]
Hi @bezanis ,

Thanks for the patch. Please could you give details on how to reproduce the problem you're trying to solve so we can verify the issue.

Cheers,

Colin

**Comment by bezanis** [comment]
Mac OSX Catalina - Chrome 77
Start scrolling in locked column and continue to scroll while mousing over to an unlocked column. Only locked column scrolls.
Start scrolling in unlocked column and continue to scroll while mousing over to locked column. Only unlocked columns scroll.
See video:
https://drive.google.com/file/d/1T1HiTfHq3t-bEQK-qNKDLRr39hXqVzke/view

**Comment by colin0117** [comment]
Thanks for the info, and the vid. Allan will take a look this evening (I don't have access to a Mac unfortunately, and can't reproduce on Linux or Windows).

**Comment by bezanis** [comment]
Tested this on a Windows machine with Chrome and the issue still occurs.
To replicate, try continuously scrolling up and down while moving the mouse back and forth between the locked and unlocked columns.

**Comment by colin0117** [comment]
Think I've got it - is this when you scroll with the keyboard using the arrow keys?

**Comment by bezanis** [comment]
Great, I was scrolling with the mouse but the down/up keys have the same issue

**Comment by AllanJard** [comment]
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues. This PR is no longer required as such.

**Pull request closed without merging**
